spring:
  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
         enable_lazy_load_no_trans: true
         dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  datasource: 
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hk_emi?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: root
    druid: 
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000  
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter-class-names:
      - stat
      - wall
      - log4j2
      connect-properties:
        druid.stat.mergeSql: true
        druid.stat.slowSqlMillis: 5000
